Womb/Controllers/CharacterController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Womb.Feats;
using Womb.Models;
using Womb.NameGeneration;
using Womb.Platform;
using Womb.ViewModels;
using Womb.WordResolver;

namespace Womb.Controllers
{
    public class CharacterController : Controller
    {
        private INameGenerator nameGenerator;
        private ICreationCountRepository creationCountRepository;
        private ICharacterSaver characterSaver;
        private IFeatResolver featResolver;

        public CharacterController(INameGenerator nameGenerator, IFeatResolver featResolver, ICreationCountRepository creationCountRepository, ICharacterSaver characterSaver)
        {
            this.nameGenerator = nameGenerator;
            this.creationCountRepository = creationCountRepository;
            this.characterSaver = characterSaver;
        }

        public async Task<IActionResult> Birth()
        {
            var character = new Character();
            character.Name = await this.nameGenerator.GenerateName(NameGenerationOptions.None);
            character.Class = ModelExtentions.AllClasses.Random();
            character.Race = Race.StandardRaces().Random();
            character.Subclass = character.Class.ChooseRandomSubclass();
            character.Subrace = character.Race.Name.ChooseRandomSubrace();
            character.Stats = Statistics.RollAll();
            character.Background = ModelExtentions.AllBackgrounds.Random();
            character.Feats = new List<Feat>() { this.featResolver.ResolveFeats().Random() }; 

            // Racial Modifiers
            foreach (var modifier in character.Race.Modifiers)
            {
                if (character.Stats.ContainsKey(modifier.Key))
                {
                    character.Stats[modifier.Key] += modifier.Value;
                }
            }

            var characterCreationCount = await this.creationCountRepository.UpdateCreationCount();

            var characterCreation = new CharacterCreationViewModel() { CharacterViewModel = new CharacterViewModel(character), CharacterCreationCount = characterCreationCount };

            return View("CharacterCreationView", characterCreation);
        }

        public async Task<IActionResult> SavedCharacters()
        {
            await Task.Delay(0);
            return Ok();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Womb/Views/Shared/CharacterPartial.cshtml
@model CharacterViewModel


<div class="container">
    <h1 class="text-success text-sm-center text-md-left" id="title-text">@Model.Name</h1>
</div>

@if (String.IsNullOrWhiteSpace(Model.Subrace))
{
    <h3 class="text-primary mx-5">@Model.Race @Model.Background</h3>
}
else
{
    <h3 class="text-primary mx-5">@Model.Subrace @Model.Race @Model.Background</h3>
}

<h3 class="text-primary mx-5">@Model.Subclass @Model.Class</h3>

<hr />

<div class="container-fluid my-2">
    <div class="row">
        @foreach (var stat in Model.Stats)
        {
            <div class="col col-md-2">
                <p class="text-center">
                    @stat.Key
                    <br />
                    @stat.Value
                </p>
            </div>
            <hr class="invisible" />
        }
    </div>
</div>

@Html.ActionLink("Refresh", "Birth", "Character", null, new { @class = "btn btn-primary btn-lg btn-block mt-5" })

Womb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @if (String.IsNullOrWhiteSpace(ViewData["Title"]?.ToString()))
    {
        <title>Womb</title>
    }
    else
    {
        <title>Womb - @ViewData["Title"]</title>
    }

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <environment include="Development">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="container wrapper">
        @RenderBody()
        <div class="push"></div>
    </div>
    <footer class="card-footer footer">
        <p>&copy; @Math.Max(2019, DateTime.Now.Year) - Demiplane.io</p>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>